---
- name: Установка zabbix агента из репозитория
  hosts: all
  become: true
  vars:
    zabbix_agent_server: zabbix.server.lc
    zabbix_agent_listenport: 10050
    zabbix_agent_listenip: 0.0.0.0
    zabbix_agent_hostname: "{{ ansible_hostname }}"

  tasks:
  - name: Загружаем настройки репозитория для конкретного дистрибутива
    ansible.builtin.get_url:
      url: https://repo.zabbix.com/zabbix/7.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+{{ ansible_distribution | lower }}{{ansible_distribution_version}}_all.deb
      dest: /tmp/{{ ansible_distribution | lower }}{{ansible_distribution_version}}_all.deb

  - name: Устанавливаем скачанное
    ansible.builtin.apt:
      deb: /tmp/{{ ansible_distribution | lower }}{{ansible_distribution_version}}_all.deb

  - name: Устанавливаем zabbix-agent2
    ansible.builtin.apt:
      name: 
        - zabbix-agent2 
        - zabbix-agent2-plugin-*
      update_cache: yes

  - name: Меняем конфиг агента
    ansible.builtin.template:
      src: zabbix_agent2.conf.j2
      dest: "/etc/zabbix/zabbix_agent2.conf"
      owner: root
      group: root
      mode: 0644
    notify:
      - restart zabbix-agent

  - name: restart zabbix-agent
    ansible.builtin.service:
      name: "zabbix-agent2"
      state: restarted
      enabled: yes
